config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :projects
  resources :subprojects, only: [:new, :create]
  resources :admin, only: [:index]
  get 'admin/user_tasks/:id', to: 'admin#user_tasks', as: 'admin_user_tasks'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :user_tasks, dependent: :destroy
  has_many :users, through: :user_tasks
  belongs_to :project

  validates :comments, presence: true
  validates :time, presence: true
  validates :day, presence: true
  validates_associated :project



end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  helper_method :sort_column, :sort_direction
  def index
    @task = Task.new
    @tasks = current_user.tasks.paginate(page: params[:page], :per_page => 25).order(sort_column + " " + sort_direction)
    @projects = Project.all.order(name: :asc)
    @task_global = Task.all.order(day: :desc)

    @user_list = User.where.not(id: current_user.id).order(name: :asc)
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="magictrackr_export_dump.xlsx"'
        #redirect_to admin_index_path
      }
    end
  end

  def show
      @current_usr_task = UserTasks.where(user_id: current_user.id)
      @tasks = Task.where(id: @current_usr_task.task_id)
  end

  def new
    @task = Task.new
    
  end

  def create

    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        current_user.tasks << @task
        @tasks = current_user.tasks
        format.js {flash.now[:notice] = "Task added"}
        #redirect_to :action => 'new'
         @user_list = User.where.not(id: current_user.id).order(name: :asc)
      else
        flash.now[:danger] = "Task not added"
        format.html { render 'new'}
        format.js { render 'err'}

      end
    end


  end

  def edit
    @task = Task.find(params[:id])

  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      current_user.tasks << @task
      flash[:success] = "Task updated"
      redirect_to tasks_path
    else
      flash[:error] = "Task not updated"
      render 'edit'
    end
  end

  def destroy
    Task.find(params[:id]).destroy
    flash[:success] = "Task Deleted"
    redirect_to tasks_path
  end


  private
  def task_params
    params.require(:task).permit(:comments, :project_id, :subproject_id, :day, :time, user_ids: [])
  end


  def correct_user
    @task = Task.find_by(id: params[:id])
    unless current_user.admin? or @task.user_ids.include? current_user.id
      redirect_to tasks_path
    end
  end

  def sort_column
    %w[day time project].include?(params[:sort]) ? params[:sort] : "day"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "DESC"
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def sorter(column, title=nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {sort: column, direction: direction}
  end


 def total_time_spent
    @timeSum = 0;

    @tasks.each do |tsk|
      @userTask = UserTask.where(task_id: tsk.id);
      if @userTask.count(:id) > 1
        @timeSum += tsk.time * @userTask.count(:id)
      else
        @timeSum += tsk.time
      end

  end
    return @timeSum
  end

end

app/views/tasks/_new.html.erb
<%= form_for(@task, method: :post, remote: true, html: {class: "form-group"}) do |f| %>
<%= evil_icons_sprite %>
  <%= f.label "Describe the task"%>
  <%= f.text_field :comments, id: "task-comments", class: "form-control" %>
  <br />
  <%= f.label "Time in minutes" %>
  <%= f.text_field :time, class: "form-control" %>
  <%= f.label "Project" %>
  <%= f.collection_select :project_id, Project.order(:name), :id, :name,
      {prompt: "Select a project"}, {class: "form-control"} %>
  <br />
  <%= f.grouped_collection_select(:subproject_id, Project.order(:name), :subprojects, :name,
      :id, :name, {prompt: "Select a subtask" },{class: "form-control"}) %>
<br / />
  <%= f.label "Date" %>
  <%= f.date_select :day,  {class: "form-control"}%>

  <br  />
  <%= f.label "Collaborators" %>
  <ul class="list-group collaborators">
    <%= f.collection_check_boxes(:user_ids, @user_list, :id, :email_or_user_name) do |box| %>

          <label class="checkbox-inline">
        <%= box.text %>
        <%= box.check_box %>
    </label>



    <% end %>
    </ul>
  <%= f.button "Add Task", class: 'btn btn-success', id: 'add-tsk-btn', data: {disable_with: "#{h evil_icon 'ei-spinner-3', size: :s}".html_safe } %>
<% end %>

app/views/tasks/_new_added.html.erb
<tr>
  <td><%= @task.day %></td>
  <td><strong> <%= Project.find_by(id: @task.project_id).name%></strong></td>
  <td>  <%= @task.comments %>  </td>
  <td><%= @task.time %></td>
  <td><%= link_to edit_task_path(@task) do %>
        <%= fa_icon "edit solid 2x", type: :solid%>
      <% end %>
      </td>
</tr>

app/views/tasks/_show_list.html.erb
<% if tasks.present? %>
<tbody id="active-tasks">
<% tasks.each do |tsk| %>
<tr>
  <td><%= tsk.day %></td>
  <td><strong> <%= projects.find_by(id: tsk.project_id).name%></strong></td>
  <td>  <%= tsk.comments %>  </td>
  <td><%= tsk.time %></td>
  <td><%= link_to edit_task_path(tsk) do %>
        <%= fa_icon "edit solid 2x", type: :solid%>
      <% end %>
</td>
</tr>
<% end %>
  </tbody>
<% end %>

app/views/tasks/create.js.erb
$("#new_task")[0].reset();
//https://stackoverflow.com/questions/10633605/clear-form-values-after-submission-ajax


$(".new_task_form").html('<%= j render partial: "tasks/new" %>');


$("#active-tasks").prepend('<%= j render "new_added" %>');

if(!document.getElementById('tsk-add')) {
$("#new-task-form").append(
  "<div class='alert alert-success' id='tsk-add'><%= flash[:notice]  %></div>")
} else {
  $("#tsk-add").innerHTML("<%= flash[:notice] %>");
}

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Edit Task</h1>

  <%= form_for(@task,  html: {class: "form-group"}) do |f| %>
    <%= f.label "Describe the task"%>
    <%= f.text_field :comments, id: "task-comments", class: "form-control" %>
    <br />
    <%= f.label "Time in minutes" %>
    <%= f.text_field :time, class: "form-control" %>
    <%= f.label "Project" %>
    <%= f.collection_select :project_id, Project.order(:name), :id, :name,
        {prompt: "Select a project"}, {class: "form-control"} %>
    <br />
    <%= f.grouped_collection_select(:subproject_id, Project.order(:name), :subprojects, :name,
        :id, :name, {prompt: "Select a subtask" },{class: "form-control"}) %>
  <br / />
    <%= f.label "Date" %>
    <%= f.date_select :day,  {class: "form-control"}%>

    <br  />
    <%= f.label "Collaborators" %>
    <ul class="list-group collaborators">
      <%= f.collection_check_boxes(:user_ids, User.where.not(id: current_user.id), :id, :email_or_user_name) do |box| %>
      <li class="list-group-item"> <%= box.check_box + box.text%> </li>

      <% end %>
      </ul>
    <br />

    <%= f.submit "Edit Task", class: 'btn btn-primary' %>

  <% end %>

  <% if current_user.admin? %>
    <div class="alert-danger">
      <h2>Danger Zone:</h2>
      <%= button_to "Delete Task", task_path(@task), data: { confirm: "Are you sure?" }, method: :delete %>
    </div>
  <% end %>

<br />
</div>

app/views/tasks/err.js.erb
if(!document.getElementById('tsk-err')) {
  $("#new-task-form").append(
    "<div class='alert alert-danger' id='tsk-err'><%= flash[:danger] %><%= j render partial: 'layouts/errors', locals: {err: @task} %> </div>")
} else {
  $("#tsk-err").innerHTML("<%= flash[:notice] %>")
}

app/views/tasks/index.html.erb
<% provide(:title, "Your Tasks") %>
<div class="container">
  <div class="row">
<h1>Welcome <%= current_user.email_or_user_name %></h1>
<% #Total time <%= total_time_spent %>
</div>
<div class="row">
<br />
Enter your tasks for the day:
</div>
<div class="row">

<%= button_tag "New Task", onclick: "showForm()", class: "btn btn-primary" %>
</div>
<div class="row">
    <div class="container-fluid" id="new_task_form">
<div id="new-task-form">
  <div class="container border rounded new-task-form">
    <%= render 'new'  %>
  </div>
</div>
</div>
</div>
<div class="shove">
<div class="row">



  <table class="table table-hover" id="current-tasks">
    <thead class="thead-dark">
      <tr>
        <th>
          <%= sorter "day", "Date:" %>
          </th>
          <th>
             Project:
            </th>
            <th>
            Comments:
              </th>
              <th>
              <%= sorter "time", "Total Time (minutes):"%>
                </th>
                <th>
                 Edit:
                  </th>
        </tr>
        </thead>

    <%= render partial: 'show_list', locals: {tasks: @tasks, projects: @projects} %>


</table>


<div class="row justify-content-sm-center">
<%= will_paginate(@tasks, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>
</div>
</div>
</div>