config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :projects
  resources :subprojects, only: [:new, :create]
  resources :admin, only: [:index]
  get 'admin/user_tasks/:id', to: 'admin#user_tasks', as: 'admin_user_tasks'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/views/admin/index.html.erb
<% provide(:title, "Admin panel") %>
<div class="container">

<h1>Welcome Admin</h1>

Select user to see stats:
<ul class="list-group">
  <% @users.each do |usr| %>

  <li class="list-group-item  list-group-item-action">
     <%= link_to usr.email_or_user_name, admin_user_tasks_path(usr) %>
    </li>
  <% end %>
  </ul>

<%= link_to "export tasks", tasks_path(format: 'xlsx'), data: {turbolinks: false}, class: "btn btn-primary" %>
</div>

app/views/admin/user_tasks.html.erb
<div class="container">
<h1><%= @user.email_or_user_name %></h1>

<% if @tasks.present?%>
<div class="shove">
<div class="row">

<table class="table table-hover" id="current-tasks">
  <thead class="thead-dark">
    <tr>
      <th>
        <%= sorter "day", "Date:" %>
        </th>
        <th>
           Project:
          </th>
          <th>
          Comments:
            </th>
            <th>
            <%= sorter "time", "Total Time (minutes):"%>
              </th>
              <th>
               Edit:
                </th>
      </tr>
      </thead>

  <%= render partial: 'tasks/show_list', locals: {tasks: @tasks, projects: @projects} %>


</table>
</div>
</div>
<% else  %>
<%= @user.email_or_user_name %> has no tasks.
<% end %>
</div>