config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :projects
  resources :subprojects, only: [:new, :create]
  resources :admin, only: [:index]
  get 'admin/user_tasks/:id', to: 'admin#user_tasks', as: 'admin_user_tasks'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :project_assocaitions
  has_many :subprojects, through: :project_assocaitions

  validates :name, uniqueness: true, presence: true, length: {minimum: 2}

  def name_length
    if name.length > 30
      name.truncate(30)
    else
      name
    end
  end

  def calculate_time(project)
    UserTask.where(task_ids: project.tasks.ids)
  end


end

app/models/task.rb
class Task < ApplicationRecord
  has_many :user_tasks, dependent: :destroy
  has_many :users, through: :user_tasks
  belongs_to :project

  validates :comments, presence: true
  validates :time, presence: true
  validates :day, presence: true
  validates_associated :project



end

app/controllers/projects_controller.rb
 class ProjectsController < ApplicationController
  before_action :authenticate_user!


  def index
    @projects = Project.all.order(name: :asc)
  end

  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks.order(day: :desc)

  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)

    if @project.save
      flash[:success] = "Project started"
      redirect_to tasks_path
    else
      flash[:error] = "project not added"
      render 'new'
    end

  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:success] = "Project updated"
      redirect_to projects_path
    else
      flash[:error] = "Project not updated"
      render 'edit'
    end
  end

  def destroy
    Project.find(params[:id]).destroy
    flash[:success] = "Project Deleted"
    redirect_to projects_path
  end



  private
  def project_params
    params.require(:project).permit(:name, :start, :precentage_complete,
                                  :summary, :go_live, subproject_ids: [])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_complete_status
    if @project.precentage_complete.nil?
      return 0
    else
      return @project.precentage_complete
    end
  end

  def project_time_spent
    @timeSum = 0;

    @tasks.each do |tsk|
      @userTask = UserTask.where(task_id: tsk.id);
      if @userTask.count(:id) > 1
        @timeSum += tsk.time * @userTask.count(:id)
      else
        @timeSum += tsk.time
      end

  end
    return @timeSum
  end

end

app/views/projects/_form.html.erb
<%= form_for(@project, html: {class: "form-group"}) do |f| %>
<%= render partial: 'layouts/errors', locals: {err: @project} %>

<%= f.label :name %>
<%= f.text_field :name, id: "project-name", class: "form-control" %>
<%= f.label :summary%>
<%= f.text_field :summary, id: "go-live", class: "form-control" %>
<%= f.label :go_live %>
<%= f.date_field :go_live, id: "go-live", class: "form-control" %>
<%= f.label :precentage_complete %>
<%= f.number_field :precentage_complete, id: "go-live", class: "form-control" %>
<%= f.label "Start Date" %>
<%= f.date_field :start, id: "date-field", class: "form-control" %>
<br />
<%= f.label "Included subprojects" %>
<br />
<ul class="list-group sub-task">

  <%= f.collection_check_boxes(:subproject_ids, Subproject.order(:name), :id,
                              :name, {class: "form-control"}) do |box| %>
  <li class="list-group-item">
  <%= box.check_box + box.text %>
  </li>
  <% end %>

  </ul>

<%= f.submit name: btn_name, class: 'btn btn-primary' %>

<% end %>

app/views/projects/edit.html.erb
<div class="container">
  <h1>Update Project</h1>
  <%= render 'form', btn_name: "Update Project"%>


<% if current_user.admin? %>
  <div class="alert-danger">
    <h2>Danger Zone:</h2>
    <%= button_to "Delete Project", project_path(@project), data: {
       confirm: "Are you sure? Deleting a project will delete all associated tasks!" }, method: :delete %>
  </div>
<% end %>
<br />
</div>

app/views/projects/index.html.erb
<% provide(:title, "All Projects") %>
<div class="container">
  <div class="row">
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <th>
        Name:
        </th>
        <th>
          Started on:
          </th>
          <th>
            Tasks:
            </th>
            <!-- <th>
              Time:
              </th> -->
            <th>
              Edit:
              </th>


      </tr>
      </thead>

      <tbody>
      <% @projects.each do |p| %>
      <tr>
        <td><%= link_to p.name, project_path(p), style: "strong" %></td>
        <td><%= p.start %></td>
        <td><%= p.tasks.count %></td>
        <td><%= link_to "edit", edit_project_path(p)%></td>

      </tr>
      <% end %>
        </tbody>


</table>

<div class="row">
<%= link_to "New Project", new_project_url, class: "btn btn-primary" %>
</div>
</div>
</div>

app/views/projects/new.html.erb
<div class="container">
	  <h1>New Project</h1>
	  <%= render 'form', btn_name: "Start Project"%>
	</div>

app/views/projects/show.html.erb
<% provide(:title, @project.name) %>
<div class="container">
  <div class="row">
    <h1><%= @project.name %></h1>
    </div>
    <div class="row">
      <div class="col-xs">Project Summary:</div>
      <div class="col-xl"><%= @project.summary %></div>
    </div>
    <div class="row">
      <div class="col-xs">Total time:</div>
      <div class="col-xl">

        <%= pluralize(project_time_spent, "minute") %>

      </div>
      </div>
      <div class="row">
        <div class="col-xs">Precentage Complete:</div>
        <div class="col-xl">
          <div class="progress">
          <div class="progress-bar progress-bar-success"
              role="progressbar"
              aria-value-now="<%= project_complete_status %>"
              aria-valuemin="0" aria-valuemax="100"
              style="width:<%= project_complete_status %>%">
              <span><%= project_complete_status %>% completed</span>
        </div>
</div>
      </div>


      </div>


    <div class="row">
      <% if @project.tasks.present? %>
      <table class="table table-hover">
        <thead class="thead-dark">

          <th>
            Task completed on:
            </th>
            <th>
              Comments:
              </th>
              <th>
                Time:
                </th>
                <% if current_user.admin? %>
                <th>
                  Collaborator(s):
                  </th>
                <th>
                   Edit:
                  </th>
                  <% end %>
          </thead>

      <tbody>
      <% @tasks.each do |tsk| %>
      <tr>
        <td><%= tsk.day %></td>
        <td>  <%= tsk.comments %>  </td>
        <td><%= tsk.time %></td>
        <% if current_user.admin %>

        <td><% User.where(id: tsk.user_ids).each do |usr| %>
        <%=  usr.email_or_user_name %>
        <% end  %></td>
        <td><%= link_to "Edit", edit_task_path(tsk) %></td>
        <% end %>
      </tr>
      <% end %>
        </tbody>
              </table>
        <% else %>
        <h2>This project has no completed tasks yet.</h2>
      <% end %>

    </div>
    </div>