config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :projects
  resources :subprojects, only: [:new, :create]
  resources :admin, only: [:index]
  get 'admin/user_tasks/:id', to: 'admin#user_tasks', as: 'admin_user_tasks'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/views/layouts/_errors.html.erb
  <% if err.errors.any? %>
  <ul>
  <% err.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= (yield(:title).empty? ? "" : "#{yield(:title)} | " )%>MagicTrackr</title>
  <meta http-equiv="x-ua-compatible" content="IE-edge"  />
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div  class="body-content">
    <div class="content">
    <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
    <h1 class="navbar-brand">MagicTrackr</h1>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expand="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <% unless user_signed_in? %>
      <ul class="navbar-nav ">
       <li class="nav-item">
          
        </li> 
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
        </li>
      </ul>
      <% end %>
      <% if user_signed_in? %>
      <ul class="navbar-nav ">
        <li class="nav-item">
          <%= link_to "My Tasks", tasks_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown"
                          role="button" data-toggle="dropdown" aria-haspopup="true"
                          aria-expanded="false">Projects</a>
            <div class="dropdown-menu" aria-laelledby="navbarDropdown">
                <%= link_to "All Projects", projects_path, class: 'dropdown-item' %>
                <%= link_to "New Project", new_project_path, class: 'dropdown-item' %>
                <%= link_to "New Subtask", new_subproject_path, class: 'dropdown-item' %>
              </div>
        </li>


        <% if current_user.admin? %>
         <li class="nav-item">
           <%= link_to "Admin", admin_index_path, class: 'nav-link' %>
         </li>
         <% end %>
      </ul>
      <ul class="navbar-nav flex-row ml-md-auto">
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown"
             role="button" data-toggle="dropdown" aria-haspopup="true"
             aria-expanded="false">Account</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Edit", edit_user_registration_path,
                 class: 'dropdown-item' %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete,
                 class: 'dropdown-item' %>
                 </div>
           </li>
      </ul>
      <% end %>
    </div>
  </nav>

 <% devise_bootstrap_mapping = {'alert' => 'danger', 'notice' => 'info'} %>

  <% flash.each do |message_type, message| %>
   <% if devise_bootstrap_mapping.keys.include? message_type %>
     <% message_type = devise_bootstrap_mapping[message_type] %>
     <% end %>
  <div class="alert alert-<%= message_type %>">
    <a href="#" data-dismiss="alert" class="close">x</a>
      <%= message %>
  </div>
  <% end %>


  <%= yield %>
    </div>
  <footer class="footer">
    <div class="container">
      <div class="row justify-content-sm-center">
        <div class="col-12">
          &copy; <%= Time.new.year %>  Travis Fantina
        </div>
      </div>
    </div>
  </footer>
  </div>



</body>
</html>